version: '3.9'
# ref: https://docs.docker.com/compose/compose-file
services:
  app:
    image: stksw/shmz_book
    build:
      args:
        - target=dev
    environment:
      TODO_ENV: dev
      PORT: 8080
      TODO_DB_HOST: todo-db
      TODO_DB_PORT: 3306
      TODO_DB_USER: todo
      TODO_DB_PASSWORD: todo
      TODO_DB_NAME: todo
    volumes:
      - .:/app
    ports:
      - '18000:8080'
  todo-db:
    image: mysql:5.7
    restart: always
    container_name: todo-db
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '33306:3306'

volumes:
  mysql-data:
